### ISSUE TITLE
Τυπογραφικό λάθος - Resume.tex & Resume.pdf

### ISSUE THREAD

**Issue by Greekforce1821** [epidrome/vita#1]
Καλησπέρα σας,

Υπάρχει ένα τυπογραφικό λάθος στο αρχείο `resume.tex` & αντίστοιχα στο `resume.pdf`. Συγκεκριμένα, εννοείτε την λέξη <ins> `μαθήματα` </ins> αλλά είναι γραμμένη ως: --> <ins> ` μθήματα ` </ins> .
Η διαδρομή είναι η εξής: /vita/gr/resume.tex & /vita/gr/resume.pdf

![Screenshot_54](https://user-images.githubusercontent.com/33377581/214841483-b7d10e57-ed33-4f10-b44d-157c0ee841a3.jpg)

**Comment by epidrome** [comment]
fixed
